
spring.datasource.url=jdbc:postgresql://localhost:5435/eventknow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# Logging configurations
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.orm.jdbc.bind=ERROR
logging.level.org.springframework.jdbc=WARN
logging.level.org.postgresql=WARN

# Google Gemini API configurations
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.model=gemini-2.5-flash

# JWT configurations
jwt.secret=dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWV2ZW50a25vdy1iYWNrZW5kLXNlY3VyaXR5LXRva2Vu
jwt.accessTokenExpMinutes=1440

#Google client configvg
google.client.id=${GOOGLE_CLIENT_ID:}
google.client.secret=${GOOGLE_CLIENT_SECRET:}

# Dev Admin email seeds
recovery.admin.emails=luanninh2005@gmail.com