spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# Logging configurations
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.orm.jdbc.bind=ERROR
logging.level.org.springframework.jdbc=WARN
logging.level.org.postgresql=WARN

# Google Gemini API configurations
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.model=gemini-3.6-flash
